### ISSUE TITLE
except clause in setup.py might not account for users without gdal/improperly setup gdal

### ISSUE THREAD

**Issue by hollybossart** [LEAF-BoiseState/janus#30]
1. I am completely unfamiliar with `gdal` and attempting to run the example. When running `python setup.py install`, I receive the following error:

```
(base) C:\Users\12088\Dropbox\janus\janus> python setup.py install
'gdal-config' is not recognized as an internal or external command,
operable program or batch file.
Traceback (most recent call last):
  File "setup.py", line 21, in <module>
    import gdal
  File "C:\Users\12088\anaconda3\lib\site-packages\gdal.py", line 2, in <module>
    from osgeo.gdal import deprecation_warn
  File "C:\Users\12088\anaconda3\lib\site-packages\osgeo\__init__.py", line 41, in <module>
    _gdal = swig_import_helper()
  File "C:\Users\12088\anaconda3\lib\site-packages\osgeo\__init__.py", line 24, in swig_import_helper
    _mod = imp.load_module('_gdal', fp, pathname, description)
  File "C:\Users\12088\anaconda3\lib\imp.py", line 242, in load_module
    return load_dynamic(name, filename, file)
  File "C:\Users\12088\anaconda3\lib\imp.py", line 342, in load_dynamic
    return _load(spec)
ImportError: DLL load failed: The specified procedure could not be found.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "setup.py", line 30, in <module>
    gdal_major = int(gdal_split[0])
ValueError: invalid literal for int() with base 10: '' 
```

I have downloaded `gdal`, though am running in a `conda` environment, which makes the path set up trickier.  Even weirder is that I am able to find which GDAL version I have. 

```
(base) C:\Users\12088\Dropbox\janus\janus> gdalinfo --version
GDAL 3.0.4, released 2020/01/28
```

**Comment by crvernon** [comment]
@hollybossart It looks like you are using Windows? If so, which version?

**Comment by crvernon** [comment]
See https://www.google.com/amp/s/tereshenkov.wordpress.com/2017/08/13/installing-gdal-with-anaconda-on-windows/amp/

**Comment by hollybossart** [comment]
Hi @crvernon, thanks for the follow-up. I am using Windows 10. I ended up getting it to work earlier today by creating and activating a new `conda` environment, where I was then able to use `conda install gdal -c conda-forge` similarly to [this solution](https://stackoverflow.com/questions/45983501/installing-gdal-with-conda-and-setting-environmental-variables). So that issue is fixed, and the `python setup.py install` now works. I'll be working through the example and will keep you posted if I have any other issues.
