### ISSUE TITLE
Include optional network_type in config file setup instructions in README

### ISSUE THREAD

**Issue by hollybossart** [LEAF-BoiseState/janus#38]
`network_type` can take one of the following options:
`'randomwalk'`, `'erdosrenyi'`, `'barabasi'`, `'smallworld'`, `'gilbert'`. These are the types of networks that the main model can accept and pass along to `im3agents/networks` for network creation. 

I've included network recognition into ConfigReader similarly to other inputs, though it may need to be double checked.

**Comment by kendrakaiser** [comment]
done
