### ISSUE TITLE
 Include decisions parameter in config file setup instructions in README

### ISSUE THREAD

**Issue by hollybossart** [LEAF-BoiseState/janus#39]
`'decision_type'` in `config.yml` can take one of the following options:
`'success'` for success bias learning, `'conformist'` for conformist bias learning, and `'profit'` for profit maximization without a network.

See `decisions()` in `model.py`. Additionally, I have included the reading in of the decision type in `ConfigReader` similarly to how the other inputs are read in, but it may need to be double checked.

**Comment by kendrakaiser** [comment]
done
